services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data/index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      
  